# Generated by Django 4.2.7 on 2025-09-17 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bus_no', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='child_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='route_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startpoint', models.CharField(max_length=200)),
                ('endpoint', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='stop_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitudea', models.FloatField()),
                ('longititude', models.FloatField()),
                ('ROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.route_table')),
            ],
        ),
        migrations.CreateModel(
            name='request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('fromstop', models.CharField(max_length=100)),
                ('tostop', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('CHILD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.child_table')),
            ],
        ),
        migrations.CreateModel(
            name='request_assign_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bus_table')),
                ('REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request_table')),
            ],
        ),
        migrations.CreateModel(
            name='parent_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bus_table')),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parent_table')),
            ],
        ),
        migrations.AddField(
            model_name='child_table',
            name='PARENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parent_table'),
        ),
        migrations.AddField(
            model_name='bus_table',
            name='ROUTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.route_table'),
        ),
        migrations.CreateModel(
            name='bus_staff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('latitudea', models.FloatField()),
                ('longititude', models.FloatField()),
                ('AssignedBus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bus_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='accident_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('Date', models.DateField()),
                ('latitudea', models.FloatField()),
                ('longititude', models.FloatField()),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bus_table')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bus_staff_table')),
            ],
        ),
    ]
