# Generated by Django 4.2.7 on 2025-09-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident_table',
            name='details',
        ),
    ]
